services:
  - type: static_site
    name: ruminster_site
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    redirects:
      - source: /*
        destination: /index.html
        statusCode: 200
